pipeline:
  build:
    image: cbrgm/drone-hugo:latest
    validate: true
    output: kanji
    url: https://obyn.io
  deploy:
    image: appleboy/drone-scp
    host: obyn.io
    source: kanji
    target: /srv/http
    secrets: [ ssh_username, ssh_key ]
    when:
      branch: [ master ]
      event: [ push ]
